#!/usr/bin/env python3
# -*- mode: python -*-

"""pbench-display-sysinfo-options - helper CLI interface for the bench-scripts
   to display the system information collection options.
"""

import sys

from pbench.agent.utils import verify_sysinfo, error_log, warn_log


good_l, bad_l = verify_sysinfo(sys.argv[1])
if bad_l:
    items = ",".join(bad_l)
else:
    items = ""
if good_l:
    if bad_l:
        # Just issue a warning for any bad items that were listed.
        warn_log(f'invalid sysinfo option, "{items}"')
    sts = 0
elif bad_l:
    # No good items, just a list of bad items.
    error_log(f'invalid sysinfo option, "{items}"')
    sts = 1
else:
    # No good or bad items, was empty or "none"
    sts = 0
sys.exit(sts)
