#!/bin/bash

echo "${0} ${*}" >> ${_testlog}

group="__bad_group__"
iteration="__bad_iteration__"
sample="__bad_sample__"

opts=$(getopt -q -o g:i:s: --longoptions "group:,iteration:,sample:" -n "getopt.sh" -- "${@}")
eval set -- "${opts}"

while true; do
	opt="${1}"
	shift
	case "${opt}" in
		-g|--group)
		if [[ -n "${1}" ]]; then
			group="${1}"
			shift
		fi
		;;
		-i|--iteration)
		if [[ -n "${1}" ]]; then
                        iteration="${1}"
			shift
		fi
		;;
		-s|--sample)
		if [[ -n "${1}" ]]; then
                        sample="${1}"
			shift
		fi
		;;
		--)
		shift
		break
		;;
	esac
done
mkdir -p "${benchmark_run_dir}/${iteration}/${sample}/tools-${group}"
